### ISSUE TITLE
Prefer the most local import when there are multiple options

### ISSUE THREAD

**Issue by peterstuart** [helixbass/eslint-plugin-known-imports#33]
For example, with this file structure:

- /src/ComponentA.tsx
- /src/B/ComponentA.tsx
- /src/B/ComponentB.tsx

attempting to use `ComponentA` from within `ComponentB.tsx` should result in `src/B/ComponentA.tsx` being imported, not the root-level `ComponentA.tsx`.

**Comment by helixbass** [comment]
Ya this has crossed my mind, I have the feeling we could use the new relative-import-path functionality to do something like getting the relative import strings for all of the potential imports and seeing which one starts with the least # of `../`'s?

**Comment by peterstuart** [comment]
Yeah. Alternatively, just don't add an import in this case? It has tripped me up a few times where it imported something I didn't expect, causing weird errors.

**Comment by helixbass** [comment]
I'd treat these as two separate ideas/settings - (a) if there are multiple potential imports, choose the "nearest" one (maybe ultimately expose the ability to choose other "strategies" for choosing between multiple imports) (b) expose a setting that lets you stay on the "safe side" and not attempt an auto-import if there are multiple potential imports

**Comment by peterstuart** [comment]
That sounds good. Especially with TS making semi-automatic imports fairly easy, I'd probably personally opt for the "safe" approach.
